[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }

sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "postgres",
    "macros",
    "chrono"
] }

thiserror = "1"
anyhow = "1"

tokio = { version = "1", features = ["full"] }
async-trait = "0.1.89"
axum = "0.8.9"
serde = { version = "1.0.228", features = ["derive"] }
tower-http = { version = "0.6.8", features = ["cors", "trace"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
tracing = "0.1.44"
argon2 = { version = "0.5", features = ["std"] }
rand = "0.8.5"
jsonwebtoken = { version = "10.3.0", default-features = false, features = ["use_pem", "rust_crypto"] }
dotenvy = "0.15.7"
